# Generated by Django 2.0.4 on 2018-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_customer_order_product_taxation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.CharField(blank=True, help_text='Enter any note about customer', max_length=500, null=True),
        ),
    ]
