# Generated by Django 2.0.4 on 2018-09-23 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_auto_20180923_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxation',
            name='tax_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='taxation',
            name='type_of_order',
            field=models.CharField(choices=[(('Taxable',), 'Taxable'), ('Non_Taxable', 'Non-Taxable')], default=('Taxable',), max_length=10),
        ),
    ]
