# Generated by Django 2.0.4 on 2018-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20180923_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxation',
            name='description',
            field=models.CharField(blank=True, help_text='Enter any note about this entry', max_length=500, null=True),
        ),
    ]
