# Generated by Django 2.0.4 on 2018-09-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_auto_20180923_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
